pipeline {
    agent any

    environment {
//         DOCKER_IMAGE = 'your-dockerhub-username/springboot-app'
        IMAGE_TAG = "${BUILD_NUMBER}"
//         REGISTRY_CREDENTIALS = 'dockerhub-creds-id'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/ajith677/jenkins.git'
            }
        }

//         stage('Build') {
//             steps {
//                 dir('demo'){
//                 sh './mvnw clean package -DskipTests=false'
//                 }
//             }
//         }
//
//         stage('Test') {
//             steps {
//             dir('demo'){
//                 sh './mvnw test'
//
//                             }
//            }
//         }

        stage('Build Docker Image') {
            steps {
            dir('demo'){
                sh "sudo docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} ."

                            }
            }
        }

//         stage('Push Docker Image') {
//             steps {
//                 script {
//                     docker.withRegistry('https://index.docker.io/v1/', REGISTRY_CREDENTIALS) {
//                         sh "docker push ${DOCKER_IMAGE}:${IMAGE_TAG}"
//                     }
//                 }
//             }
//         }

        stage('Deploy') {
            steps {
                sh "sudo docker stop springboot-app || true && docker rm springboot-app || true"
                sh "sudo docker run -d --name springboot-app -p 8081:8081 ${DOCKER_IMAGE}:${IMAGE_TAG}"
            }
        }
    }

    post {
        success {
            echo '✅ Application deployed successfully!'
        }
        failure {
            echo '❌ Deployment failed.'
        }
    }
}
